variables:
    DOCKER_DRIVER: overlay
    CI_REGISTRY_IMAGE_WITH_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
    DOCKER_HUB_IMAGE_WITH_TAG: "$DOCKER_HUB_IMAGE:$CI_COMMIT_REF_NAME"

stages:
  - build
  - deploy

.template-docker-image: &docker-stage
    image: docker:latest
    services:
      - docker:dind
    only:
      - latest
      - /^\d+(\.\d{1,2})?$/
    tags:
      - docker

build:docker-image:
    <<: *docker-stage
    stage: build
    script:
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker build -t $CI_REGISTRY_IMAGE_WITH_TAG --no-cache=true .
      - docker push $CI_REGISTRY_IMAGE_WITH_TAG

deploy:docker-image:
    <<: *docker-stage
    stage: deploy
    script:
      - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      - docker pull $CI_REGISTRY_IMAGE_WITH_TAG
      - docker tag $CI_REGISTRY_IMAGE_WITH_TAG $DOCKER_HUB_IMAGE_WITH_TAG
      - docker push $DOCKER_HUB_IMAGE_WITH_TAG
